"use client";

import Link from "next/link";
import PageShell from "@/components/common/PageShell";
import { useAuth } from "@/components/common/AuthContext";

export default function Page() {
  const { user, openAuth } = useAuth();
  if (!user) return <PageShell title="Buyer dashboard" description="Track orders, saved items, and recent activity."><div className="site-card max-w-md p-8 text-center"><h2 className="text-2xl font-bold text-slate-950">Sign in to shop</h2><p className="mt-3 text-sm leading-7 text-slate-600">Create a client account to save products, manage your cart, and track orders.</p><button type="button" onClick={() => openAuth("login", "client")} className="mt-6 rounded-[10px] bg-accent-400 px-5 py-3 text-sm font-bold text-black">Sign in as a client</button></div></PageShell>;
  return <PageShell title="Buyer dashboard" description="Your client account for finding, saving, and purchasing campus products."><div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><section className="site-card p-6 sm:p-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-brand-700">Client account</p><h2 className="mt-3 text-3xl font-bold text-slate-950">Welcome, {user.name}</h2><p className="mt-3 text-sm leading-7 text-slate-600">Browse verified campus sellers, compare full product details, and keep every purchase in one place.</p><div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Orders</p><p className="mt-2 text-2xl font-bold text-slate-950">0</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Saved</p><p className="mt-2 text-2xl font-bold text-slate-950">0</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Cart items</p><p className="mt-2 text-2xl font-bold text-slate-950">0</p></div></div></section><aside className="site-card p-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-brand-700">Quick actions</p><div className="mt-5 space-y-3"><Link href="/marketplace" className="flex items-center justify-between rounded-xl border border-slate-200 p-4 text-sm font-bold text-slate-950">Browse marketplace <span>→</span></Link><Link href="/marketplace/favourites" className="flex items-center justify-between rounded-xl border border-slate-200 p-4 text-sm font-bold text-slate-950">View saved listings <span>→</span></Link><Link href="/cart" className="flex items-center justify-between rounded-xl border border-slate-200 p-4 text-sm font-bold text-slate-950">Open cart <span>→</span></Link></div></aside></div></PageShell>;
}
